# This is a basic workflow to help you get started with Actions

name: Build and Test Windows

on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    defaults:
      run:
         shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: git mingw-w64-x86_64-toolchain
               
      - name: generate environment  
        shell: cmd
        run: |
          powershell -c ./build-aux/envdiff.ps1
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          powershell -c ./build-aux/envdiff.ps1 > c:\msys64\%USERNAME%\.visualstudio.sh
      - name: CI-Build      
        run: |
          echo 'Running in MSYS2!'
          pwd -W
          cd ~
          pwd -W
          source ~/.visualstudio.sh
          echo $PATH
          echo $LIBPATH
